name: FragaliciousOrigins
description: Sir Fraagalicious's take on the Origins Mod.
author: Sir_Fragalicious
website: github.com
version: '${project.version}'
main: com.github.sanforjr2021.FragaliciousOrigins
api-version: 1.13
commands:
  origin:
    description: Select your origin by using /origin choose Origin
    usage: /origin choose <OriginName>
  leavebed:
    description: Leave your bed as a nocturnal origin
    usage: /leavebed
  primaryability:
    description: Use your primary ability
    usage: /primaryAbility
  secondaryability:
    description: Use your secondary ability (if applicable)
    usage: /secondaryAbility
  shulkchest:
    description: View another players shulk inventory
    usage: /shulkchest <player>
    permission: fragalicious.origins.command.shulkchest
  heat:
    description: Set the heat of a player.
    usage: /heat <temperature> <player>
    permission: fragalicious.origins.command.heat